[project]
name = "dbcp"
version = "0.1.0"
description = "A Python package for disciplined biconvex programming."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cvxpy>=1.7.3",
    "numpy>=2.3.3",
]
